# Generated by Django 4.2.6 on 2023-10-12 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator(message='Email is invalid')]),
        ),
    ]
