# Generated by Django 4.2.6 on 2023-10-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='token',
            field=models.CharField(default=1, max_length=300, unique=True),
        ),
    ]
