# Generated by Django 4.2.6 on 2023-10-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0004_alter_destination_share_publicly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
